In [2]:
import pandas as pd
import numpy as np
import mlflow
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from mlflow.models import infer_signature

In [3]:
#set the tracking uri

mlflow.set_tracking_uri(uri="http://127.0.0.1:5000")

In [4]:
#load the dataset 
X,y=datasets.load_iris(return_X_y=True)


In [8]:
#split the data into trainig and test sets
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

#define the model hyperparameters
params={"penalty":'l2',"solver":"lbfgs","max_iter":1000,"multi_class":"auto","random_state":8888}

#train the model
lr=LogisticRegression(**params)
lr.fit(x_train,y_train)




/Users/suryasadasivam/DataScience /project/Mlflow/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=8888)

In [9]:
##Prediction on the test data
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0,
       0, 1, 0, 0, 0, 0, 1, 2])

In [11]:
y_test

array([1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0,
       0, 1, 0, 0, 0, 0, 1, 2])

In [10]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

1.0


In [12]:
#create new mlflow experiment
mlflow.set_experiment("Mlflow Quickstart")

#start mlflow run
with mlflow.start_run():
    #log the hyperparameters:
    mlflow.log_params(params)
    ##log accuracy metric
    mlflow.log_metric("accuracy",accuracy)

    #set tag for the experiments
    mlflow.set_tag("Training Info","Basic LR model for iris data")
    
    #infer the model signature

    signature=infer_signature(x_train,lr.predict(x_train))

    #log the model
    model_info=mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signature,
        input_example=x_train,
        registered_model_name="tracking-quickstart"

    )


2025/04/23 19:05:50 INFO mlflow.tracking.fluent: Experiment with name 'Mlflow Quickstart' does not exist. Creating a new experiment.
Successfully registered model 'tracking-quickstart'.
2025/04/23 19:05:52 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tracking-quickstart, version 1


🏃 View run clean-wasp-739 at: http://127.0.0.1:5000/#/experiments/197735067171661857/runs/a148e3280c424341aa5f500779a51590
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/197735067171661857


Created version '1' of model 'tracking-quickstart'.


In [14]:
#define the model hyperparameters
params={"solver":"newton-cg","max_iter":1000,"multi_class":"auto","random_state":8898}

#train the model
lr=LogisticRegression(**params)
lr.fit(x_train,y_train)


/Users/suryasadasivam/DataScience /project/Mlflow/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=8898,
                   solver='newton-cg')

In [15]:
#start mlflow run
with mlflow.start_run():
    #log the hyperparameters:
    mlflow.log_params(params)
    ##log accuracy metric
    mlflow.log_metric("accuracy",accuracy)

    #set tag for the experiments
    mlflow.set_tag("Training Info","Basic LR model for iris data")
    
    #infer the model signature

    signature=infer_signature(x_train,lr.predict(x_train))

    #log the model
    model_info=mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signature,
        input_example=x_train,
        registered_model_name="tracking-quickstart"

    )


Registered model 'tracking-quickstart' already exists. Creating a new version of this model...
2025/04/23 19:16:53 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tracking-quickstart, version 2


🏃 View run unique-crane-573 at: http://127.0.0.1:5000/#/experiments/197735067171661857/runs/f1bfc03afa964f8eaa42d1351a593894
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/197735067171661857


Created version '2' of model 'tracking-quickstart'.


In [21]:
pip install uv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 3.8 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Inferencing and validating Model

In [24]:

logged_model = 'runs:/f1bfc03afa964f8eaa42d1351a593894/iris_model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

predictions=loaded_model.predict(x_test)

iris_features_name=datasets.load_iris().feature_names

result=pd.DataFrame(x_test,columns=iris_features_name)

result["actual_class"]=y_test

result["predicted_class"]=predictions
result

sepal length (cm)  sepal width (cm)  ...  actual_class  predicted_class
0                 6.0               2.2  ...             1                1
1                 6.8               2.8  ...             1                1
2                 5.1               3.3  ...             0                0
3                 6.4               2.9  ...             1                1
4                 6.3               3.3  ...             2                2
5                 6.6               2.9  ...             1                1
6                 5.1               3.4  ...             0                0
7                 5.5               2.4  ...             1                1
8                 6.9               3.1  ...             1                1
9                 5.4               3.9  ...             0                0
10                6.8               3.2  ...             2                2
11                6.7               3.1  ...             2                2
12                6.7               3.3  ...             2                2
13                5.9               3.0  ...             2                2
14                6.3               2.5  ...             1                1
15                7.2               3.0  ...             2                2
16                5.1               3.7  ...             0                0
17                5.0               2.0  ...             1                1
18                6.4               3.2  ...             2                2
19                6.2               2.8  ...             2                2
20                6.3               2.5  ...             2                2
21                5.4               3.4  ...             0                0
22                4.8               3.4  ...             0                0
23                5.9               3.0  ...             1                1
24                4.9               3.0  ...             0                0
25                4.5               2.3  ...             0                0
26                4.6               3.1  ...             0                0
27                5.1               3.8  ...             0                0
28                5.7               2.9  ...             1                1
29                6.7               3.0  ...             2                2

[30 rows x 6 columns]

ML flow Model Registry Tracking

The MLFLow model registry component is a centralized model store, set of APIs and UI to collaboratively manage the full lifecycle of an MLflow Model.It provides model lineage(which MLflow experiment and run produced the model),Model versioinig, model aliasing, model tagging, and annotation

In [25]:
 #start mlflow run
with mlflow.start_run():
    #log the hyperparameters:
    mlflow.log_params(params)
    ##log accuracy metric
    mlflow.log_metric("accuracy",0.98)

    #set tag for the experiments
    mlflow.set_tag("Training Info3","Basic LR model for iris data")
    
    #infer the model signature

    signature=infer_signature(x_train,lr.predict(x_train))

    #log the model
    model_info=mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signature,
        input_example=x_train,

    )

🏃 View run unique-stork-141 at: http://127.0.0.1:5000/#/experiments/197735067171661857/runs/e54fd6eb75e046e3a60eb288e931f7f9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/197735067171661857


##Inferencing from model from model registry

In [26]:
import mlflow.sklearn
model_name="tracking-quickstart"
model_version='latest'

model_uri=f"models:/{model_name}/{model_version}"

model=mlflow.sklearn.load_model(model_uri)

model

LogisticRegression(max_iter=1000, multi_class='auto', random_state=8898,
                   solver='newton-cg')

In [27]:
model_uri

'models:/tracking-quickstart/latest'

In [28]:
y_pred_new=model.predict(x_test)
y_pred_new

array([1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0,
       0, 1, 0, 0, 0, 0, 1, 2])